FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends build-essential unixodbc-dev gcc g++ ca-certificates && \
    pip install --no-cache-dir -r /app/requirements.txt && \
    apt-get remove -y build-essential gcc g++ && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

COPY ./app /app/app

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
